# Generated by Django 6.1.1 on 2026-09-16 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acervo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do acervo', max_length=255, verbose_name='Título')),
                ('autor', models.CharField(help_text='Nome do autor ou criador', max_length=150, verbose_name='Autor')),
                ('ano', models.IntegerField(help_text='Ano em que foi publicado', validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Ano de Publicação')),
                ('tipo_acervo', models.CharField(choices=[('digital', 'Digital'), ('fisico', 'Físico')], default='fisico', help_text='Se é digital ou físico', max_length=10, verbose_name='Tipo de Acervo')),
                ('categoria', models.CharField(choices=[('000', '000 - Generalidades e Informação'), ('100', '100 - Filosofia e Psicologia'), ('200', '200 - Religião e Teologia'), ('300', '300 - Ciências Sociais e Direito'), ('400', '400 - Linguística e Idiomas'), ('500', '500 - Ciências Puras (Exatas e Naturais)'), ('600', '600 - Ciências Aplicadas (Tecnologia)'), ('700', '700 - Artes e Recreação'), ('800', '800 - Literatura'), ('900', '900 - História e Geografia')], help_text='Classificação Decimal de Dewey', max_length=100, verbose_name='Categoria (DDC)')),
                ('disponivel', models.BooleanField(default=True, help_text='Se o acervo está disponível para empréstimo', verbose_name='Disponível')),
                ('descricao', models.TextField(blank=True, help_text='Descrição ou resumo do acervo', null=True, verbose_name='Descrição')),
                ('isbn', models.CharField(blank=True, help_text='Código ISBN do livro', max_length=20, null=True, unique=True, verbose_name='ISBN')),
                ('editora', models.CharField(blank=True, help_text='Nome da editora', max_length=150, null=True, verbose_name='Editora')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Acervo',
                'verbose_name_plural': 'Acervos',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['titulo'], name='acervo_acer_titulo_d30838_idx'), models.Index(fields=['categoria'], name='acervo_acer_categor_199b98_idx'), models.Index(fields=['tipo_acervo'], name='acervo_acer_tipo_ac_179aed_idx')],
            },
        ),
    ]
